using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace mapkey
{
    class Program
    {
        [DllImport("user32.dll")]
        public static extern uint MapVirtualKey(uint uCode, uint uMapType);
        static void Main(string[] args)
        {
            Console.WriteLine("S_LBUTTON : " + (ushort)MapVirtualKey(0x01, 0));
            Console.WriteLine("S_RBUTTON : " + (ushort)MapVirtualKey(0x02, 0));
            Console.WriteLine("S_CANCEL : " + (ushort)MapVirtualKey(0x03, 0));
            Console.WriteLine("S_MBUTTON : " + (ushort)MapVirtualKey(0x04, 0));
            Console.WriteLine("S_XBUTTON1 : " + (ushort)MapVirtualKey(0x05, 0));
            Console.WriteLine("S_XBUTTON2 : " + (ushort)MapVirtualKey(0x06, 0));
            Console.WriteLine("S_BACK : " + (ushort)MapVirtualKey(0x08, 0));
            Console.WriteLine("S_Tab : " + (ushort)MapVirtualKey(0x09, 0));
            Console.WriteLine("S_CLEAR : " + (ushort)MapVirtualKey(0x0C, 0));
            Console.WriteLine("S_Return : " + (ushort)MapVirtualKey(0x0D, 0));
            Console.WriteLine("S_SHIFT : " + (ushort)MapVirtualKey(0x10, 0));
            Console.WriteLine("S_CONTROL : " + (ushort)MapVirtualKey(0x11, 0));
            Console.WriteLine("S_MENU : " + (ushort)MapVirtualKey(0x12, 0));
            Console.WriteLine("S_PAUSE : " + (ushort)MapVirtualKey(0x13, 0));
            Console.WriteLine("S_CAPITAL : " + (ushort)MapVirtualKey(0x14, 0));
            Console.WriteLine("S_KANA : " + (ushort)MapVirtualKey(0x15, 0));
            Console.WriteLine("S_HANGEUL : " + (ushort)MapVirtualKey(0x15, 0));
            Console.WriteLine("S_HANGUL : " + (ushort)MapVirtualKey(0x15, 0));
            Console.WriteLine("S_JUNJA : " + (ushort)MapVirtualKey(0x17, 0));
            Console.WriteLine("S_FINAL : " + (ushort)MapVirtualKey(0x18, 0));
            Console.WriteLine("S_HANJA : " + (ushort)MapVirtualKey(0x19, 0));
            Console.WriteLine("S_KANJI : " + (ushort)MapVirtualKey(0x19, 0));
            Console.WriteLine("S_Escape : " + (ushort)MapVirtualKey(0x1B, 0));
            Console.WriteLine("S_CONVERT : " + (ushort)MapVirtualKey(0x1C, 0));
            Console.WriteLine("S_NONCONVERT : " + (ushort)MapVirtualKey(0x1D, 0));
            Console.WriteLine("S_ACCEPT : " + (ushort)MapVirtualKey(0x1E, 0));
            Console.WriteLine("S_MODECHANGE : " + (ushort)MapVirtualKey(0x1F, 0));
            Console.WriteLine("S_Space : " + (ushort)MapVirtualKey(0x20, 0));
            Console.WriteLine("S_PRIOR : " + (ushort)MapVirtualKey(0x21, 0));
            Console.WriteLine("S_NEXT : " + (ushort)MapVirtualKey(0x22, 0));
            Console.WriteLine("S_END : " + (ushort)MapVirtualKey(0x23, 0));
            Console.WriteLine("S_HOME : " + (ushort)MapVirtualKey(0x24, 0));
            Console.WriteLine("S_LEFT : " + (ushort)MapVirtualKey(0x25, 0));
            Console.WriteLine("S_UP : " + (ushort)MapVirtualKey(0x26, 0));
            Console.WriteLine("S_RIGHT : " + (ushort)MapVirtualKey(0x27, 0));
            Console.WriteLine("S_DOWN : " + (ushort)MapVirtualKey(0x28, 0));
            Console.WriteLine("S_SELECT : " + (ushort)MapVirtualKey(0x29, 0));
            Console.WriteLine("S_PRINT : " + (ushort)MapVirtualKey(0x2A, 0));
            Console.WriteLine("S_EXECUTE : " + (ushort)MapVirtualKey(0x2B, 0));
            Console.WriteLine("S_SNAPSHOT : " + (ushort)MapVirtualKey(0x2C, 0));
            Console.WriteLine("S_INSERT : " + (ushort)MapVirtualKey(0x2D, 0));
            Console.WriteLine("S_DELETE : " + (ushort)MapVirtualKey(0x2E, 0));
            Console.WriteLine("S_HELP : " + (ushort)MapVirtualKey(0x2F, 0));
            Console.WriteLine("S_APOSTROPHE : " + (ushort)MapVirtualKey(0xDE, 0));
            Console.WriteLine("S_0 : " + (ushort)MapVirtualKey(0x30, 0));
            Console.WriteLine("S_1 : " + (ushort)MapVirtualKey(0x31, 0));
            Console.WriteLine("S_2 : " + (ushort)MapVirtualKey(0x32, 0));
            Console.WriteLine("S_3 : " + (ushort)MapVirtualKey(0x33, 0));
            Console.WriteLine("S_4 : " + (ushort)MapVirtualKey(0x34, 0));
            Console.WriteLine("S_5 : " + (ushort)MapVirtualKey(0x35, 0));
            Console.WriteLine("S_6 : " + (ushort)MapVirtualKey(0x36, 0));
            Console.WriteLine("S_7 : " + (ushort)MapVirtualKey(0x37, 0));
            Console.WriteLine("S_8 : " + (ushort)MapVirtualKey(0x38, 0));
            Console.WriteLine("S_9 : " + (ushort)MapVirtualKey(0x39, 0));
            Console.WriteLine("S_A : " + (ushort)MapVirtualKey(0x41, 0));
            Console.WriteLine("S_B : " + (ushort)MapVirtualKey(0x42, 0));
            Console.WriteLine("S_C : " + (ushort)MapVirtualKey(0x43, 0));
            Console.WriteLine("S_D : " + (ushort)MapVirtualKey(0x44, 0));
            Console.WriteLine("S_E : " + (ushort)MapVirtualKey(0x45, 0));
            Console.WriteLine("S_F : " + (ushort)MapVirtualKey(0x46, 0));
            Console.WriteLine("S_G : " + (ushort)MapVirtualKey(0x47, 0));
            Console.WriteLine("S_H : " + (ushort)MapVirtualKey(0x48, 0));
            Console.WriteLine("S_I : " + (ushort)MapVirtualKey(0x49, 0));
            Console.WriteLine("S_J : " + (ushort)MapVirtualKey(0x4A, 0));
            Console.WriteLine("S_K : " + (ushort)MapVirtualKey(0x4B, 0));
            Console.WriteLine("S_L : " + (ushort)MapVirtualKey(0x4C, 0));
            Console.WriteLine("S_M : " + (ushort)MapVirtualKey(0x4D, 0));
            Console.WriteLine("S_N : " + (ushort)MapVirtualKey(0x4E, 0));
            Console.WriteLine("S_O : " + (ushort)MapVirtualKey(0x4F, 0));
            Console.WriteLine("S_P : " + (ushort)MapVirtualKey(0x50, 0));
            Console.WriteLine("S_Q : " + (ushort)MapVirtualKey(0x51, 0));
            Console.WriteLine("S_R : " + (ushort)MapVirtualKey(0x52, 0));
            Console.WriteLine("S_S : " + (ushort)MapVirtualKey(0x53, 0));
            Console.WriteLine("S_T : " + (ushort)MapVirtualKey(0x54, 0));
            Console.WriteLine("S_U : " + (ushort)MapVirtualKey(0x55, 0));
            Console.WriteLine("S_V : " + (ushort)MapVirtualKey(0x56, 0));
            Console.WriteLine("S_W : " + (ushort)MapVirtualKey(0x57, 0));
            Console.WriteLine("S_X : " + (ushort)MapVirtualKey(0x58, 0));
            Console.WriteLine("S_Y : " + (ushort)MapVirtualKey(0x59, 0));
            Console.WriteLine("S_Z : " + (ushort)MapVirtualKey(0x5A, 0));
            Console.WriteLine("S_LWIN : " + (ushort)MapVirtualKey(0x5B, 0));
            Console.WriteLine("S_RWIN : " + (ushort)MapVirtualKey(0x5C, 0));
            Console.WriteLine("S_APPS : " + (ushort)MapVirtualKey(0x5D, 0));
            Console.WriteLine("S_SLEEP : " + (ushort)MapVirtualKey(0x5F, 0));
            Console.WriteLine("S_NUMPAD0 : " + (ushort)MapVirtualKey(0x60, 0));
            Console.WriteLine("S_NUMPAD1 : " + (ushort)MapVirtualKey(0x61, 0));
            Console.WriteLine("S_NUMPAD2 : " + (ushort)MapVirtualKey(0x62, 0));
            Console.WriteLine("S_NUMPAD3 : " + (ushort)MapVirtualKey(0x63, 0));
            Console.WriteLine("S_NUMPAD4 : " + (ushort)MapVirtualKey(0x64, 0));
            Console.WriteLine("S_NUMPAD5 : " + (ushort)MapVirtualKey(0x65, 0));
            Console.WriteLine("S_NUMPAD6 : " + (ushort)MapVirtualKey(0x66, 0));
            Console.WriteLine("S_NUMPAD7 : " + (ushort)MapVirtualKey(0x67, 0));
            Console.WriteLine("S_NUMPAD8 : " + (ushort)MapVirtualKey(0x68, 0));
            Console.WriteLine("S_NUMPAD9 : " + (ushort)MapVirtualKey(0x69, 0));
            Console.WriteLine("S_MULTIPLY : " + (ushort)MapVirtualKey(0x6A, 0));
            Console.WriteLine("S_ADD : " + (ushort)MapVirtualKey(0x6B, 0));
            Console.WriteLine("S_SEPARATOR : " + (ushort)MapVirtualKey(0x6C, 0));
            Console.WriteLine("S_SUBTRACT : " + (ushort)MapVirtualKey(0x6D, 0));
            Console.WriteLine("S_DECIMAL : " + (ushort)MapVirtualKey(0x6E, 0));
            Console.WriteLine("S_DIVIDE : " + (ushort)MapVirtualKey(0x6F, 0));
            Console.WriteLine("S_F1 : " + (ushort)MapVirtualKey(0x70, 0));
            Console.WriteLine("S_F2 : " + (ushort)MapVirtualKey(0x71, 0));
            Console.WriteLine("S_F3 : " + (ushort)MapVirtualKey(0x72, 0));
            Console.WriteLine("S_F4 : " + (ushort)MapVirtualKey(0x73, 0));
            Console.WriteLine("S_F5 : " + (ushort)MapVirtualKey(0x74, 0));
            Console.WriteLine("S_F6 : " + (ushort)MapVirtualKey(0x75, 0));
            Console.WriteLine("S_F7 : " + (ushort)MapVirtualKey(0x76, 0));
            Console.WriteLine("S_F8 : " + (ushort)MapVirtualKey(0x77, 0));
            Console.WriteLine("S_F9 : " + (ushort)MapVirtualKey(0x78, 0));
            Console.WriteLine("S_F10 : " + (ushort)MapVirtualKey(0x79, 0));
            Console.WriteLine("S_F11 : " + (ushort)MapVirtualKey(0x7A, 0));
            Console.WriteLine("S_F12 : " + (ushort)MapVirtualKey(0x7B, 0));
            Console.WriteLine("S_F13 : " + (ushort)MapVirtualKey(0x7C, 0));
            Console.WriteLine("S_F14 : " + (ushort)MapVirtualKey(0x7D, 0));
            Console.WriteLine("S_F15 : " + (ushort)MapVirtualKey(0x7E, 0));
            Console.WriteLine("S_F16 : " + (ushort)MapVirtualKey(0x7F, 0));
            Console.WriteLine("S_F17 : " + (ushort)MapVirtualKey(0x80, 0));
            Console.WriteLine("S_F18 : " + (ushort)MapVirtualKey(0x81, 0));
            Console.WriteLine("S_F19 : " + (ushort)MapVirtualKey(0x82, 0));
            Console.WriteLine("S_F20 : " + (ushort)MapVirtualKey(0x83, 0));
            Console.WriteLine("S_F21 : " + (ushort)MapVirtualKey(0x84, 0));
            Console.WriteLine("S_F22 : " + (ushort)MapVirtualKey(0x85, 0));
            Console.WriteLine("S_F23 : " + (ushort)MapVirtualKey(0x86, 0));
            Console.WriteLine("S_F24 : " + (ushort)MapVirtualKey(0x87, 0));
            Console.WriteLine("S_NUMLOCK : " + (ushort)MapVirtualKey(0x90, 0));
            Console.WriteLine("S_SCROLL : " + (ushort)MapVirtualKey(0x91, 0));
            Console.WriteLine("S_LeftShift : " + (ushort)MapVirtualKey(0xA0, 0));
            Console.WriteLine("S_RightShift : " + (ushort)MapVirtualKey(0xA1, 0));
            Console.WriteLine("S_LeftControl : " + (ushort)MapVirtualKey(0xA2, 0));
            Console.WriteLine("S_RightControl : " + (ushort)MapVirtualKey(0xA3, 0));
            Console.WriteLine("S_LMENU : " + (ushort)MapVirtualKey(0xA4, 0));
            Console.WriteLine("S_RMENU : " + (ushort)MapVirtualKey(0xA5, 0));
            Console.WriteLine("S_BROWSER_BACK : " + (ushort)MapVirtualKey(0xA6, 0));
            Console.WriteLine("S_BROWSER_FORWARD : " + (ushort)MapVirtualKey(0xA7, 0));
            Console.WriteLine("S_BROWSER_REFRESH : " + (ushort)MapVirtualKey(0xA8, 0));
            Console.WriteLine("S_BROWSER_STOP : " + (ushort)MapVirtualKey(0xA9, 0));
            Console.WriteLine("S_BROWSER_SEARCH : " + (ushort)MapVirtualKey(0xAA, 0));
            Console.WriteLine("S_BROWSER_FAVORITES : " + (ushort)MapVirtualKey(0xAB, 0));
            Console.WriteLine("S_BROWSER_HOME : " + (ushort)MapVirtualKey(0xAC, 0));
            Console.WriteLine("S_VOLUME_MUTE : " + (ushort)MapVirtualKey(0xAD, 0));
            Console.WriteLine("S_VOLUME_DOWN : " + (ushort)MapVirtualKey(0xAE, 0));
            Console.WriteLine("S_VOLUME_UP : " + (ushort)MapVirtualKey(0xAF, 0));
            Console.WriteLine("S_MEDIA_NEXT_TRACK : " + (ushort)MapVirtualKey(0xB0, 0));
            Console.WriteLine("S_MEDIA_PREV_TRACK : " + (ushort)MapVirtualKey(0xB1, 0));
            Console.WriteLine("S_MEDIA_STOP : " + (ushort)MapVirtualKey(0xB2, 0));
            Console.WriteLine("S_MEDIA_PLAY_PAUSE : " + (ushort)MapVirtualKey(0xB3, 0));
            Console.WriteLine("S_LAUNCH_MAIL : " + (ushort)MapVirtualKey(0xB4, 0));
            Console.WriteLine("S_LAUNCH_MEDIA_SELECT : " + (ushort)MapVirtualKey(0xB5, 0));
            Console.WriteLine("S_LAUNCH_APP1 : " + (ushort)MapVirtualKey(0xB6, 0));
            Console.WriteLine("S_LAUNCH_APP2 : " + (ushort)MapVirtualKey(0xB7, 0));
            Console.WriteLine("S_OEM_1 : " + (ushort)MapVirtualKey(0xBA, 0));
            Console.WriteLine("S_OEM_PLUS : " + (ushort)MapVirtualKey(0xBB, 0));
            Console.WriteLine("S_OEM_COMMA : " + (ushort)MapVirtualKey(0xBC, 0));
            Console.WriteLine("S_OEM_MINUS : " + (ushort)MapVirtualKey(0xBD, 0));
            Console.WriteLine("S_OEM_PERIOD : " + (ushort)MapVirtualKey(0xBE, 0));
            Console.WriteLine("S_OEM_2 : " + (ushort)MapVirtualKey(0xBF, 0));
            Console.WriteLine("S_OEM_3 : " + (ushort)MapVirtualKey(0xC0, 0));
            Console.WriteLine("S_OEM_4 : " + (ushort)MapVirtualKey(0xDB, 0));
            Console.WriteLine("S_OEM_5 : " + (ushort)MapVirtualKey(0xDC, 0));
            Console.WriteLine("S_OEM_6 : " + (ushort)MapVirtualKey(0xDD, 0));
            Console.WriteLine("S_OEM_7 : " + (ushort)MapVirtualKey(0xDE, 0));
            Console.WriteLine("S_OEM_8 : " + (ushort)MapVirtualKey(0xDF, 0));
            Console.WriteLine("S_OEM_102 : " + (ushort)MapVirtualKey(0xE2, 0));
            Console.WriteLine("S_PROCESSKEY : " + (ushort)MapVirtualKey(0xE5, 0));
            Console.WriteLine("S_PACKET : " + (ushort)MapVirtualKey(0xE7, 0));
            Console.WriteLine("S_ATTN : " + (ushort)MapVirtualKey(0xF6, 0));
            Console.WriteLine("S_CRSEL : " + (ushort)MapVirtualKey(0xF7, 0));
            Console.WriteLine("S_EXSEL : " + (ushort)MapVirtualKey(0xF8, 0));
            Console.WriteLine("S_EREOF : " + (ushort)MapVirtualKey(0xF9, 0));
            Console.WriteLine("S_PLAY : " + (ushort)MapVirtualKey(0xFA, 0));
            Console.WriteLine("S_ZOOM : " + (ushort)MapVirtualKey(0xFB, 0));
            Console.WriteLine("S_NONAME : " + (ushort)MapVirtualKey(0xFC, 0));
            Console.WriteLine("S_PA1 : " + (ushort)MapVirtualKey(0xFD, 0));
            Console.WriteLine("S_OEM_CLEAR : " + (ushort)MapVirtualKey(0xFE, 0));
            Console.ReadLine();
        }
    }
}
